version: 2
sources:
    - name: in.c-testExecutorConfigMetadata
      freshness:
        warn_after:
            count: 1
            period: day
      database: '{{ env_var("DBT_KBC_DEV_DATABASE") }}'
      schema: in.c-testExecutorConfigMetadata
      loaded_at_field: '"_timestamp"'
      tables:
        - name: out
          quoting:
            database: true
            schema: true
            identifier: true
          columns: []
